version: '3'
services:
  traefik:
    image: traefik:v2.10
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    networks:
      - gtm-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/configs/traefik.yaml:/etc/traefik/traefik.yaml
      - ./traefik/configs/traefik_dynamic.yaml:/etc/traefik/traefik_dynamic.yaml

  redis:
    image: redislabs/redisgraph:2.12.9
    networks:
      - gtm-network
    ports:
      - "6379:6379"
    labels:
      - traefik.enable=false

  api:
    build: .
    ports:
      - "9300"
    networks:
      - gtm-network
    environment:
      - GTM_REDIS_HOST=redis

networks:
  gtm-network:
    name: gtm-network