version: '3'

services:
  traefik:
    image: traefik:v2.10
    command:
      - --api.insecure=true

    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    networks:
      - gtm-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yaml:/etc/traefik/traefik.yaml
      - ./traefik_dynamic.yaml:/etc/traefik/traefik_dynamic.yaml
      - ./cert.pem:/etc/traefik/pki/cert.pem
      - ./privkey.key:/etc/traefik/pki/privkey.key
  redis:
    image: redislabs/redisgraph:2.12.9
    networks:
      - gtm-network
    ports:
      - "6379:6379"
  api:
    build: .
    ports:
      - "9300"
    networks:
      - gtm-network
    environment:
      - GTM_REDIS_HOST=redis
    labels:
      - traefik.enable=true
      - traefik.http.routers.gtmrouter.rule=Host(`gtm.delary.dev`)||Host(`delary.dev`)
      - traefik.http.routers.gtmrouter.tls=true
networks:
  gtm-network:
    name: gtm-network